version: "3.7"

services:
  db:
    image: postgres:latest
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 45432:5432

  migration:
    build: .
    env_file: .env
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python manage.py migrate'
    volumes:
      - .:/app
    depends_on:
      - db

  api:
    build: .
    env_file: .env
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python manage.py runserver 0.0.0.0:8000'
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    ports:
      - 8000:8000

    depends_on:
      - db
      - migration
volumes:
  pgdata:
