# Generated by Django 4.0.6 on 2022-07-15 21:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('birth_place', models.CharField(max_length=50)),
                ('race', models.CharField(max_length=50)),
                ('age', models.IntegerField(null=True)),
                ('description', models.TextField(max_length=255)),
                ('health_points', models.IntegerField()),
                ('status', models.CharField(choices=[('Healthy', 'Ht'), ('Dead', 'Dd')], max_length=50)),
                ('mana_points', models.IntegerField()),
                ('intelligence_points', models.IntegerField()),
                ('strength_points', models.IntegerField()),
                ('stamina_points', models.IntegerField()),
                ('dexterity_points', models.IntegerField()),
                ('attack_points', models.IntegerField()),
                ('defense_points', models.IntegerField()),
                ('exp_points', models.IntegerField(default=1)),
                ('max_exp_points', models.IntegerField(default=100)),
                ('level_up_points', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='classes.class')),
            ],
        ),
    ]
