# Generated by Django 4.0.6 on 2022-07-14 20:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('birth_place', models.CharField(max_length=50)),
                ('race', models.CharField(max_length=50)),
                ('age', models.IntegerField(null=True)),
                ('description', models.TextField(max_length=255)),
                ('health_points', models.IntegerField()),
                ('status', models.CharField(choices=[('healthy', 'Ht'), ('dead', 'Dd')], max_length=50)),
                ('mana_points', models.IntegerField()),
                ('inteligence_points', models.IntegerField()),
                ('strength_points', models.IntegerField()),
                ('stamina_points', models.IntegerField()),
                ('dexterity_points', models.IntegerField()),
                ('attack_points', models.IntegerField()),
                ('defense_points', models.IntegerField()),
                ('exp_points', models.IntegerField()),
                ('max_exp_points', models.IntegerField()),
                ('level_up_points', models.IntegerField()),
                ('level', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
