# Generated by Django 4.0.6 on 2022-07-14 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('journeys', '0001_initial'),
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='journey_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='journeys.journey'),
        ),
    ]
