# Generated by Django 4.0.6 on 2022-07-15 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0002_initial'),
        ('characters', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='journey_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='journeys.journey'),
        ),
        migrations.AlterField(
            model_name='character',
            name='status',
            field=models.CharField(choices=[('Healthy', 'Ht'), ('Dead', 'Dd')], max_length=50),
        ),
    ]
