# Generated by Django 4.0.6 on 2022-07-15 15:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_alter_character_journey_id_alter_character_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='inteligence_points',
            new_name='intelligence_points',
        ),
        migrations.AlterField(
            model_name='character',
            name='exp_points',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='character',
            name='level',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='character',
            name='level_up_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='max_exp_points',
            field=models.IntegerField(default=100),
        ),
    ]
