# Generated by Django 4.0.6 on 2022-07-15 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_rename_inteligence_points_character_intelligence_points_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='class_id',
            new_name='class_name',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='journey_id',
            new_name='journey',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='user_id',
            new_name='user',
        ),
    ]
