# Generated by Django 4.0.6 on 2022-07-15 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0002_initial'),
        ('characters', '0006_rename_class_id_character_class_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='journey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='journeys.journey'),
        ),
    ]
