# Generated by Django 4.0.6 on 2022-07-14 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('Weapon', 'Weapon'), ('Armor', 'Armor'), ('Artifact', 'Artifact')], default='Weapon', max_length=50)),
                ('rarity', models.CharField(choices=[('Common', 'Common'), ('Uncommon', 'Uncommon'), ('Rare', 'Rare')], default='Common', max_length=50)),
                ('precision', models.IntegerField()),
                ('min_level', models.IntegerField()),
            ],
        ),
    ]
