# Generated by Django 4.0.6 on 2022-07-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('WP', 'Weapon'), ('AM', 'Armor'), ('AR', 'Artifact')], default='WP', max_length=50)),
                ('rarity', models.CharField(choices=[('CM', 'Common'), ('UC', 'Uncommon'), ('RR', 'Rare')], default='CM', max_length=50)),
                ('precision', models.IntegerField()),
                ('min_level', models.IntegerField()),
            ],
        ),
    ]
