# Generated by Django 4.0.6 on 2022-07-19 17:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('systems', '0001_initial'),
        ('bonus', '0001_initial'),
        ('characters', '0001_initial'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('Weapon', 'Weapon'), ('Armor', 'Armor'), ('Artifact', 'Artifact')], default='Weapon', max_length=50)),
                ('rarity', models.CharField(choices=[('Common', 'Common'), ('Uncommon', 'Uncommon'), ('Rare', 'Rare')], default='Common', max_length=50)),
                ('precision', models.IntegerField()),
                ('min_level', models.IntegerField()),
                ('bonus', models.ManyToManyField(related_name='items', to='bonus.bonus')),
                ('characters', models.ManyToManyField(related_name='inventories', to='characters.character')),
                ('classes', models.ManyToManyField(related_name='items', to='classes.class')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='systems.system')),
            ],
        ),
    ]
