# Generated by Django 4.0.6 on 2022-07-14 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='rarity',
            field=models.CharField(choices=[('Common', 'Common'), ('Uncommon', 'Uncommon'), ('Rare', 'Rare')], default='Common', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('Weapon', 'Weapon'), ('Armor', 'Armor'), ('Artifact', 'Artifact')], default='Weapon', max_length=50),
        ),
    ]
