# Generated by Django 4.0.6 on 2022-07-19 17:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=255)),
                ('min_level', models.IntegerField()),
                ('max_level', models.IntegerField()),
                ('max_players', models.IntegerField()),
                ('table_link', models.CharField(max_length=255)),
                ('status', models.CharField(default='Created', max_length=50)),
                ('started_at', models.CharField(max_length=255, null=True)),
                ('ended_at', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
