# Generated by Django 4.0.6 on 2022-07-14 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=255)),
                ('min_level', models.IntegerField()),
                ('max_level', models.IntegerField()),
                ('max_players', models.IntegerField()),
                ('table_link', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('created', 'Cr'), ('start', 'St'), ('finished', 'Fs')], max_length=50)),
                ('started_at', models.CharField(max_length=255)),
                ('ended_at', models.CharField(max_length=255)),
            ],
        ),
    ]
