# Generated by Django 4.0.6 on 2022-07-14 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
